---
- hosts: tag_Name_Application
  user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
    - file:
        path: /home/ubuntu/project/Project-6/Application/
        owner: ubuntu
        group: ubuntu
        # when specifying mode using octal numbers, add a leading 0
        mode: 0600
    - name: install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-simplejson)
    - name: install Apache
      apt: name={{item}} state=present update_cache=yes
      with_items:
        apache2

    - name: ensure apache2 started
      service: name=apache2 state=started enabled=yes

    - name: Copy files to remote host
      copy:
        src: /home/ubuntu/Application/index.html
        dest: /var/www/html/
       # owner: root
       # group: root
       # mode: 0777
